version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10 # (1)
    commands:
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin  # (2)
  pre_build:
    commands:
      - npm install # (3)
  build:
    commands:
      - docker build -t senthil4861/discussion-frontend . # (5)
      - docker push senthil4861/discussion-frontend